- frontend/.eslintrc.json
- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.tsx
- frontend/src/components/AlreadyInQueueModal.tsx
- frontend/src/components/ConnectedElseWhereModal.tsx
- frontend/src/components/SignupPage.tsx
- frontend/src/components/index.tsx
- frontend/src/constants.tsx
- frontend/src/constants/index.tsx
- frontend/src/pages/MatchPage.tsx
- matching-service/.env.example
- matching-service/.eslintrc.json
- matching-service/package-lock.json
- matching-service/package.json
- matching-service/src/Server.ts
- matching-service/src/constants/index.ts
- matching-service/src/data/SidToUserMap.ts
- matching-service/src/data/UserQueue.ts
- matching-service/src/data/index.ts
- matching-service/src/index.ts
- matching-service/src/socket/authMiddleware.ts
- matching-service/src/socket/index.ts
- matching-service/src/socket/joinQueue.ts
- matching-service/src/socket/leaveQueue.ts
- user-service/src/controllers/UserCtrl.ts
READY
#7 
I dun think any new features.
Last PR was a POC, this PR solidifies the concept.
1. Added error handling / edge case handling (and the data structures to support that)
2. Added modals (feel free to edit => this is for testing)
3. Also added middleware so only those with valid JWT can establish a connection. (We need to discuss on this. This is mostly due to invalidation of JWT)
1. I need to stop people from queuing when they are already in a room (as a double check => cuz if have room we should auto redirect to the room).
2. Allow people to leave the room.
4. Handle disconnections in the room.
5. We need to redirect the user to a room, if they are already in the room.
> feat(match): Update and refactor socket logic

- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.tsx
- frontend/src/components/common/NavBar.tsx
- frontend/src/contexts/AuthContext.tsx
- frontend/src/pages/LoginPage.tsx
- frontend/src/pages/MatchPage.tsx
IN DEVELOPMENT
Create a navbar common component for use in the application.
Include the navbar in the match page.
* Only the logout button is functional at the moment
* [] Have you generated documentation for your changes?
> feat(NavBar): create Navbar common component

- user-service/src/controllers/UserCtrl.ts
- user-service/src/controllers/authMiddleware.ts
READY 
JWT is signed upon login but not verified during navigation. This could lead to issues because JWT can expire while the user is still using the web application. Let's create middleware to authenticate the JWT and refresh the expiration.
Backend, no screenshots, verified by pair programming.
> Create middleware for JWT Authentication

- user-service/src/controllers/UserCtrl.ts
- user-service/src/model/repository.ts
- user-service/src/model/user-orm.ts
READY
The application does not support deletion of users. To introduce this feature to users, let's do the following:
* verify user access token and password
* Ensure that username matches provided password
* Delete user from database if token is valid and username matches password
closes #15
> Create delete functionality for backend

- frontend/src/configs.tsx
- frontend/src/constants/index.tsx
- frontend/src/pages/SettingsPage.tsx
~~READY~~ | IN DEVELOPMENT | ~~HOLD~~
Add delete functionality for delete button in user settings.
NA
Add style for tab panel
> Add functionality for delete user button in settings

- frontend/src/components/common/TabPanel.tsx
- frontend/src/configs.tsx
- frontend/src/constants/index.tsx
- frontend/src/pages/SettingsPage.tsx
- user-service/package-lock.json
- user-service/package.json
- user-service/src/model/user-model.ts
READY
Fix bug where password field for delete account and change password shared the same prop
> bugfix(frontend): Fix bug where password field for delete account and change password shared the same prop

- frontend/src/components/common/TabPanel.tsx
- frontend/src/configs.tsx
- frontend/src/constants/index.tsx
- frontend/src/pages/SettingsPage.tsx
- user-service/package-lock.json
- user-service/package.json
- user-service/src/model/user-model.ts
READY
Add numerical user id to UserModel using mongoose-sequence plugin.
> feat(user): Add numerical user id to DB

- docs/peerdep-api/api-doc.md
- docs/peerdep-api/peerdep-api.postman_collection.json
- question-service/.env.example
- question-service/package-lock.json
- question-service/package.json
- question-service/src/Server.ts
- question-service/src/controllers/QuestionCtrl.ts
- question-service/src/index.ts
- question-service/src/model/question-model.ts
- question-service/src/model/question-orm.ts
- question-service/src/model/repository.ts
- question-service/tsconfig.json
IN DEVELOPMENT 
- Created model, controller and server for question service backend
- Implemented API endpoints for adding questions, deleting questions and getting a random question from the pool of questions
- Update postman documentation
Add question:
Delete question:
Get random question:
> Create question service backend

- collaboration-service/docker-compose.yml
- collaboration-service/package-lock.json
- collaboration-service/package.json
- collaboration-service/src/Server.ts
- collaboration-service/src/constants/index.ts
- collaboration-service/src/index.ts
- collaboration-service/src/redis/index.ts
- collaboration-service/src/socket/authMiddleware.ts
- frontend/.eslintrc.json
- frontend/src/components/editor/Editor.tsx
- frontend/src/constants/index.tsx
- frontend/src/pages/RoomPage.tsx
- matching-service/src/controllers/authMiddleware.ts
READY
@BrendonLau After leave room, navigate is not working. There is some race condition too. Make sure roomUuid is fetch before doing anything. And also like the room close it can still enter through the room/uuid link.
A few sentences describing the overall goals of the pull request's commits.
> feat(collab): Allow users to collab

- README.md
- frontend/src/components/room/Chat.tsx
- frontend/src/components/room/QuestionModal.tsx
- frontend/src/configs.tsx
- frontend/src/contexts/SocketContext.tsx
- frontend/src/pages/MatchPage.tsx
- frontend/src/pages/RoomPage.tsx
- matching-service/src/controllers/roomController.ts
READY 
Update readme
Bug fixes:
1. Fix able to enter wrong room url bug
2. Fix the bug when both users matched, only one or none will enter the room
3. Fix the room leave button
Flow:
1. Both users click on "easy" in match page
2. Any user click on "leave" both users will be kicked back to match
A few screenshots display the changes made by the pull request.
> feat(collab): integrate collaboration and fix bugs

- README.md
- frontend/src/components/room/QuestionModal.tsx
- frontend/src/pages/SettingsPage.tsx
Fix variable name and disable eslint for a particular line
> Fix(Question/Setting): Minor fix

- docs/peerdep-api/api-doc.md
- docs/peerdep-api/peerdep-api.postman_collection.json
- history-service/src/constants/index.ts
- history-service/src/controllers/SessionCtrl.ts
- history-service/src/model/session-model.ts
- history-service/src/model/session-orm.ts
READY
Refractor and update duplication check for existing room Uuid
> feat(history): update duplication checks and refractor

- collaboration-service/package-lock.json
- collaboration-service/package.json
- collaboration-service/src/Server.ts
- collaboration-service/src/constants/index.ts
- collaboration-service/src/socket/authMiddleware.ts
- frontend/src/contexts/SocketContext.tsx
- frontend/src/pages/RoomPage.tsx
- history-service/src/controllers/SessionCtrl.ts
- history-service/src/model/session-model.ts
- matching-service/docker-compose.yml
- matching-service/prisma/migrations/20221022155840_added_closed_at_to_room/migration.sql
- matching-service/prisma/schema.prisma
- matching-service/src/services/RoomService.ts
READY
A few sentences describing the overall goals of the pull request's commits.
Create session on room close.
> feat(history): Create session when room closes

- README.md
- collaboration-service/package-lock.json
- communication-service/package-lock.json
- docs/peerdep-api/api-doc.md
- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.tsx
- frontend/src/components/common/NavBar.tsx
- frontend/src/components/history/EditorView.tsx
- frontend/src/components/history/Table.tsx
- frontend/src/components/room/QuestionModal.tsx
- frontend/src/configs.tsx
- frontend/src/pages/HistoryPage.tsx
- frontend/src/pages/SettingsPage.tsx
- history-service/package-lock.json
- matching-service/package-lock.json
- question-service/src/Server.ts
- question-service/src/controllers/QuestionCtrl.ts
READY
1. Created History page 
2. Created Table where users can view past records and select pagination options
3. Created EditorView which shows read-only code from a past session when the "View" button is clicked
4. Added a button that routes to the history page on the nav bar
5. Updated QuestionModal to include jwt authorization header in the axios request
_History Page and Table_
_Editor View_
_Updated NavBar_
* [] Have you generated documentation for your changes?
> feat(history): Implement frontend

- question-service/package-lock.json
- question-service/package.json
- question-service/src/controllers/AuthMiddleWare.ts
- question-service/src/controllers/QuestionCtrl.ts
READY
The Question Service get question endpoint does not authenticate users of the api. To ensure that the endpoint is not abused, we will check if a valid jwt is provided.
This will close #57.
Success
Invalid token
No token
> Implement User Authentication for Question Service

- collaboration-service/.dockerignore
- collaboration-service/Dockerfile
- collaboration-service/src/redis/index.ts
- communication-service/.dockerignore
- communication-service/Dockerfile
- docker-compose.yml
- frontend/.dockerignore
- frontend/Dockerfile
- frontend/package-lock.json
- history-service/.dockerignore
- history-service/Dockerfile
- matching-service/.dockerignore
- matching-service/Dockerfile
- question-service/.dockerignore
- question-service/Dockerfile
- user-service/.dockerignore
- user-service/Dockerfile
READY 
A few sentences describing the overall goals of the pull request's commits.
> feat(docker): Dockerize microservices except for frontend

- frontend/src/components/index.tsx
- frontend/src/pages/LoginPage.tsx
> Fix bigbang export error

- frontend/src/components/history/EditorView.tsx
READY
Fix error with EditorView typography
> Update EditorView props

- frontend/src/pages/LoginPage.tsx
READY 
Update login button colour
> Update login button colour

- frontend/src/components/history/EditorView.tsx
- frontend/src/components/history/Table.tsx
- frontend/src/pages/LoginPage.tsx
description overlay navbar
fix the navbar overlay issue
> Update historypage bug
